### ISSUE TITLE
Settings of ocp-indent itself

### ISSUE THREAD

**Issue by smondet** [314eter/atom-ocaml-indent#1]
It would be nice if one could configure ocp-indent from the "settings" UI
(settings to add to the `-c` option, like `-c strict_with=always,with=0,strict_comments=false`)

**Comment by 314eter** [comment]
Isn't it better to configure this in a `.ocp-indent` file? That's more flexible (different projects can have different options), editor independent, and can be version controlled. But maybe this should be mentioned in the configuration page or README.

I think the best solution would be to
1. mention `.ocp-indent` in README and configuration
2. add one option to configure the command line arguments

Do you agree?

**Comment by smondet** [comment]
I agree 👍 

(I also use the `.ocp-indent` file; I was just wondering if having the command line option settings in the UI would be more beginner friendly)
