### ISSUE TITLE
ocaml indent

### ISSUE THREAD

**Issue by doyeka** [314eter/atom-ocaml-indent#2]
```
 print_string "Hello World\ "   hello.ml2:1 LFUTF-8OCaml Failed to spawn command ocp-indent. Make sure ocp-indent is installed and on your PATH.
```

I keep getting this error when trying to type code in atom. Could you help me with the remedy?

**Comment by 314eter** [comment]
You should have ocp-indent installed, and available in your path. If that's the case, try opening atom from the command line.
