### ISSUE TITLE
Default keybind shadows window:toggle-dev-tools core keybind

### ISSUE THREAD

**Issue by AndreasDahl** [314eter/atom-ocaml-indent#6]

**Comment by 314eter** [comment]
I don't have a mac, so I didn't notice. Which other keybinding do you suggest?

**Comment by AndreasDahl** [comment]
Hmm.. looking at other packages. The popular [Atom Typescript](https://atom.io/packages/atom-typescript) has a `format-code` command on `ctrl-alt-l`/`cmd-alt-l` in typescript. That might be a good hotkey.

**Comment by 314eter** [comment]
I added `ctrl-alt-f` for **f**ormat **f**ile (this is what most other formatters I'm using do), and kept `ctrl-alt-i` (**i**ndent l**i**ne) for backward compatibility.
